# Generated by Django 5.1 on 2024-09-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_framework_api_key", "0005_auto_20220110_1102"),
        ("toxic_comment_classification_api", "0004_project_classifierapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifierapikey",
            name="key",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_framework_api_key.apikey",
            ),
        ),
    ]
