# Generated by Django 5.1 on 2024-09-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toxic_comment_classification_api", "0005_classifierapikey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifierapikey",
            name="key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
