# Generated by Django 5.1 on 2024-09-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_framework_api_key", "0005_auto_20220110_1102"),
        ("toxic_comment_classification_api", "0006_alter_classifierapikey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classifierapikey",
            name="key",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classification_key",
                to="rest_framework_api_key.apikey",
            ),
        ),
    ]
